### Get initial page
GET http://localhost:3000/users


### Register a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "name": "Wellinton",
  "phone": "47991484848",
  "email": "wellinton658@email.com",
  "cpf": "123456789101112",
  "password": "greatPassword",
  "akjhdkjhs": "lskdjlkjasd"
}


### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "wellinton658@email.com",
  "password": "greatPassword"
}


### Get all States
GET http://localhost:3000/state


### Get states by id
GET http://localhost:3000/state/5


### Get all cities by stateId
GET http://localhost:3000/city/state/24


### Get all cities by cityId
GET http://localhost:3000/city/560


### Post new Address
POST http://localhost:3000/address
Content-Type: application/json

{
  "cep": "89633-590",
  "cityId": 560,
  "numberAddress": 588
}


### Get user by Id
GET http://localhost:3000/users/5


### Get Addresses by UserId
GET http://localhost:3000/address/1