### Get initial page
GET http://localhost:3000/users


### Register a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "name": "Wellinton",
  "phone": "47991484848",
  "email": "wellinto65@email.com",
  "cpf": "12345678910",
  "password": "greatPassword",
  "akjhdkjhs": "lskdjlkjasd"
}


### Get all States
GET http://localhost:3000/state


### Get all cities by stateId
GET http://localhost:3000/city/11