### Get initial page
GET http://localhost:3000/users


### Register a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "name": "Wellinton",
  "phone": "47991484848",
  "email": "wellinto65@email.com",
  "cpf": "12345678910",
  "password": "greatPassword",
  "akjhdkjhs": "lskdjlkjasd"
}


### Get all States
GET http://localhost:3000/state


### Get all cities by stateId
GET http://localhost:3000/city/24


### Post new Address
POST http://localhost:3000/address
Content-Type: application/json

{
  "cep": "89633-590",
  "cityId": 560,
  "numberAddress": 588
}


### Get user by Id
GET http://localhost:3000/users/1


### Get Addresses by UserId
GET http://localhost:3000/address/5